project:
  type: website
  output-dir: docs

website:
  title: "From Coach to Old Navy"

format:
  html:
    theme: default
    toc: true
    rendering: embed-resources
    code-fold: true
    code-tools: true

bibliography: references.bib
nocite: |
  @*

resources:
  - doc/blog.qmd
